# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1egoogle/protobuf/wrappers.proto\"E\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"H\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"v\n\x14RegisterUserResponse\x12#\n\x0fsuccess_payload\x18\x01 \x01(\x0b\x32\n.auth.User\x12\x15\n\rerror_payload\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x05\"(\n\x14\x43heckUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t2\x9a\x01\n\x0b\x41uthService\x12\x41\n\x08register\x12\x19.auth.RegisterUserRequest\x1a\x1a.auth.RegisterUserResponse\x12H\n\x0e\x63heck_username\x12\x1a.auth.CheckUsernameRequest\x1a\x1a.google.protobuf.BoolValueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=52
  _USER._serialized_end=121
  _REGISTERUSERREQUEST._serialized_start=123
  _REGISTERUSERREQUEST._serialized_end=195
  _REGISTERUSERRESPONSE._serialized_start=197
  _REGISTERUSERRESPONSE._serialized_end=315
  _CHECKUSERNAMEREQUEST._serialized_start=317
  _CHECKUSERNAMEREQUEST._serialized_end=357
  _AUTHSERVICE._serialized_start=360
  _AUTHSERVICE._serialized_end=514
# @@protoc_insertion_point(module_scope)
